name: Publish Ads
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'  # Every 12 hours
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v4
      - name: set permissions
        run: chmod +x ./scripts/run.sh
      - name: publish content
        run: make ad
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHANNEL_ID: "@stlcollectordev"
          AD_FILE: ./scripts/list.txt
