name: Publish Ads DEV
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v4
      - name: set permissions
        run: chmod +x ./scripts/run.sh
      - name: publish content
        run: make ad
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHANNEL_ID: ${{ vars.CHANNEL_ID }}
          AD_FILE: ./scripts/list.txt